#!/bin/bash
# Botflow sim egress containment + build-VM->WARP forwarding guard.
#
# HARD RULE: never reload the MAIN ruleset (pfctl -f /etc/pf.conf) on a healthy
# system. A main-ruleset reload flushes anchors that system services insert
# dynamically — the Virtualization.framework/vmnet NAT rules AND Cloudflare
# WARP's com.cloudflare.warp_svc firewall — which silently kills guest egress
# (xcodebuild 74: SPM cannot reach github). /etc/pf.conf's own header warns
# about exactly this. All loads below are ANCHOR-SCOPED (pfctl -a X -f file).
#
# Anchors managed here:
#   com.botflow.simegress — per-uid containment for the simhost user (502).
#   com.botflow.vmnat     — routes build-VM (192.168.64.0/24) traffic into the
#                           Cloudflare WARP utun with source-NAT to WARP's own
#                           tunnel address, so guest egress exits via Cloudflare
#                           instead of the home IP. vmnet's own NAT cannot do
#                           this (it breaks under WARP, whose PF firewall RSTs
#                           any non-tunnel flow). The utun name can change when
#                           WARP reconnects, so this guard regenerates the
#                           anchor file whenever the interface moves.
#                           FAIL-CLOSED: if WARP is down, the route-to rules
#                           keep pointing at a dead utun and guests simply lose
#                           egress — they never fall back to leaking the raw
#                           home IP.
#
# NOTE: guest->HOST traffic (any host-owned IP) is delivered by vmnet in
# userspace and BYPASSES PF entirely — the block rules for it below are defense
# in depth only. The real control is sshd's "Match Address 192.168.64.0/24 →
# DenyUsers *" (/etc/ssh/sshd_config.d/100-botflow-deny-vm-subnet.conf).
ANCHOR=com.botflow.simegress
VMNAT=com.botflow.vmnat
VMNAT_FILE=/etc/pf.anchors/$VMNAT
CONF=/etc/pf.conf
LOG=/var/log/pf-egress-guard.log
log() { echo "$(date '+%Y-%m-%d %H:%M:%S') $1" >> "$LOG"; }

[ -f "/etc/pf.anchors/$ANCHOR" ] || { log "anchor file missing — cannot enforce"; exit 1; }

# Drift check 1: pf.conf lost our anchor refs (macOS update rewrote it).
# Re-append so the next boot picks them up — but do NOT force a main reload.
if ! grep -q "$ANCHOR" "$CONF" 2>/dev/null; then
  printf '\n# Botflow sim egress containment (re-added by pf-egress-load.sh)\nanchor "%s"\nload anchor "%s" from "/etc/pf.anchors/%s"\n' \
    "$ANCHOR" "$ANCHOR" "$ANCHOR" >> "$CONF"
  log "re-added simegress anchor refs to $CONF"
fi
# The two vmnat refs must be checked INDEPENDENTLY. They live in different
# sections and have been observed to drift apart: with only the nat-anchor
# present, egress still worked (so it looked healthy) while every guest
# ISOLATION rule sat in an anchor nothing ever evaluated. A single
# `grep -q com.botflow.vmnat` would have called that state "fine".
NEEDS_RELOAD=0
if ! grep -q "^nat-anchor \"$VMNAT\"" "$CONF" 2>/dev/null; then
  # nat-anchor must live in the translation section, before any filter rules.
  /usr/bin/sed -i '' "s|nat-anchor \"com.apple/\*\"|nat-anchor \"com.apple/*\"\nnat-anchor \"$VMNAT\"|" "$CONF"
  log "re-added vmnat NAT-anchor ref to $CONF"
  NEEDS_RELOAD=1
fi
if ! grep -q "^anchor \"$VMNAT\"" "$CONF" 2>/dev/null; then
  printf '\n# Botflow build-VM -> WARP forwarding (populated at runtime by pf-egress-load.sh)\nanchor "%s"\n' "$VMNAT" >> "$CONF"
  log "re-added vmnat FILTER-anchor ref to $CONF (guest isolation was NOT being evaluated)"
  NEEDS_RELOAD=1
fi
# NEVER let pf.conf load the vmnat anchor at BOOT. Its route-to rules name the
# WARP utun, which does not exist until the WARP daemon connects — pfctl then
# fails on an unknown interface and the ENTIRE main ruleset load fails, taking
# vmnet's NAT and the com.apple anchors down with it. The anchor is declared in
# pf.conf but populated only here, at runtime, once the interface exists.
if grep -q "load anchor \"$VMNAT\"" "$CONF" 2>/dev/null; then
  /usr/bin/sed -i '' "\|load anchor \"$VMNAT\"|d" "$CONF"
  log "removed boot-time 'load anchor $VMNAT' from $CONF (unsafe: utun absent at boot)"
fi

# Drift check 2: simegress rules gone from the live ruleset -> anchor-scoped load.
if ! pfctl -a "$ANCHOR" -sr 2>/dev/null | grep -q simblock-loopback; then
  pfctl -a "$ANCHOR" -f "/etc/pf.anchors/$ANCHOR" >/dev/null 2>&1
  log "simegress anchor was empty — reloaded (anchor-scoped)"
fi

# Drift check 3: vmnat — find the WARP utun (its tunnel address is stable per
# registration: 172.16.0.2 for this consumer registration).
WARP_IF=$(ifconfig 2>/dev/null | awk '/^utun[0-9]+:/{u=substr($1,1,length($1)-1)} /inet 172\.16\.0\.2 /{print u; exit}')
if [ -n "$WARP_IF" ]; then
  if ! grep -q "on $WARP_IF " "$VMNAT_FILE" 2>/dev/null; then
    cat > "$VMNAT_FILE" <<VMNATEOF
# GENERATED by pf-egress-load.sh — do not edit; the WARP utun name is dynamic.
# Build-VM traffic -> WARP tunnel. See infra/pf-egress-load.sh in expo-stream.
nat on $WARP_IF inet from 192.168.64.0/24 to any -> 172.16.0.2
pass in quick on bridge100 inet proto udp from 192.168.64.0/24 to 192.168.64.1 port {53, 67} keep state
pass in quick on bridge100 inet proto tcp from 192.168.64.0/24 to 192.168.64.1 port 53 keep state
block return in quick on bridge100 inet from 192.168.64.0/24 to 192.168.64.1
block return in quick on bridge100 inet from 192.168.64.0/24 to { 10.0.0.0/8, 100.64.0.0/10, 169.254.0.0/16, 172.16.0.0/12, 192.168.0.0/16 }
pass in quick on bridge100 route-to ($WARP_IF 172.16.0.2) inet proto tcp from 192.168.64.0/24 to any flags S/SA keep state
pass in quick on bridge100 route-to ($WARP_IF 172.16.0.2) inet proto udp from 192.168.64.0/24 to any keep state
pass in quick on bridge100 route-to ($WARP_IF 172.16.0.2) inet proto icmp from 192.168.64.0/24 to any keep state
VMNATEOF
    pfctl -a "$VMNAT" -f "$VMNAT_FILE" >/dev/null 2>&1
    log "vmnat: WARP interface is $WARP_IF — regenerated + loaded anchor"
  elif ! pfctl -a "$VMNAT" -sn 2>/dev/null | grep -q "nat on"; then
    pfctl -a "$VMNAT" -f "$VMNAT_FILE" >/dev/null 2>&1
    log "vmnat: anchor was empty — reloaded (anchor-scoped)"
  fi
else
  # WARP is down. Install the BLOCK half only — no route-to, so the anchor still
  # parses without the utun. Guests keep local DHCP/DNS (so they boot and get an
  # IP; a VM that never gets one makes the pool retry forever) but no egress:
  # fail-closed, never a fallback to the raw home IP.
  if ! grep -q "WARP-DOWN" "$VMNAT_FILE" 2>/dev/null; then
    cat > "$VMNAT_FILE" <<'VMNATDOWN'
# GENERATED by pf-egress-load.sh — WARP-DOWN fail-closed ruleset (no route-to).
pass in quick on bridge100 inet proto udp from 192.168.64.0/24 to 192.168.64.1 port {53, 67} keep state
pass in quick on bridge100 inet proto tcp from 192.168.64.0/24 to 192.168.64.1 port 53 keep state
block return in quick on bridge100 inet from 192.168.64.0/24 to any
VMNATDOWN
    pfctl -a "$VMNAT" -f "$VMNAT_FILE" >/dev/null 2>&1
    log "vmnat: no WARP interface — installed fail-closed ruleset (guests: DHCP/DNS only)"
  fi
fi

# A newly-added anchor REF only takes effect on a main-ruleset reload, which
# would flush vmnet's NAT and WARP's own anchor — unacceptable to do from an
# unattended 300s timer (that is the bug this whole file exists to avoid). The
# ref is now persisted in pf.conf, so the next boot picks it up naturally; until
# then, say so loudly rather than pretending the rules are live.
if [ "$NEEDS_RELOAD" = "1" ]; then
  log "WARNING: pf.conf refs were repaired but are NOT live until a main reload." \
      "Run 'pfctl -f /etc/pf.conf' then restart host-agent (recreates vmnet NAT)" \
      "and confirm WARP re-asserts its anchor — or simply reboot."
fi

# PF itself must be enabled (idempotent).
pfctl -s info 2>/dev/null | grep -q "Status: Enabled" || pfctl -e >/dev/null 2>&1

if ! pfctl -a "$ANCHOR" -sr 2>/dev/null | grep -q simblock-loopback; then
  log "WARNING: anchor $ANCHOR is EMPTY after load — sim egress is NOT contained"
fi
